### ISSUE TITLE
Enquire with the trustees about getting more people access to MailChimp

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#112]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-08-20.md#specific

**Comment by RealOrangeOne** [comment]
I've sent an email to Jimmy, who historically has been the one handling the mailchimp side of things.

**Comment by RealOrangeOne** [comment]
Due to the current mailchimp plan, we're not able to add more people to the mailchimp account.

The trustees would prefer us to either share credentials, or move over to using Google Groups, I suggest we do the latter.

We've used it in the past for volunteer communications, and it's worked rather well!

I've done some testing based on how we use the MailChimp lists, and i'm confident we can replicate how it works using Google Groups, with some minor changes to the signup process.

I'm happy to consider this ticket solved, however will open some new tickets to track making the required changes to use Google Groups.
