### ISSUE TITLE
Send email to Kit Team Committee outlining plans and timelines

### ISSUE THREAD

**Issue by sedders123** [srobo/competition-team-minutes#118]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-08-27.md#specific

**Comment by RealOrangeOne** [comment]
I believe this is covered by the meeting the trustees are planning to have in the next couple weeks with both teams present?

> we are keen to have a meeting to make sure that you are all happy with the split of responsibilities between the two teams and discuss any areas of concern. Also, we need to be sure that there is nothing major missing (that might not get done)!

**Comment by PeterJCLaw** [comment]
Interesting. If that meeting happens this weekend then yes. Otherwise IMO that won't cut it. Part of the point of us getting on with this is to avoid ending up with it being mid-September before we talk about what the goals are.

Since we know that we want to hit an end-of-September ready-to-Kickstart state time is already pretty tight, so I think we should be doing this ~now. (I had actually hoped that this would happen a couple of weeks back)

**Comment by PeterJCLaw** [comment]
Here's a terrible draft in case it helps:

> Hi Kit Team,
> 
> We're looking forward to working with you to make SR2020 the best competition yet!
> 
> With that in mind, we'd like to share our plans for the competition year and how
you can help with that.
> 
> In order to get the year off to a prompt start, as well as to allow some buffer
> in case things slip, we're aiming to be completely ready for Kickstart by the
> end of September. That's the date by which we'd like to have the rules written,
> the microgames prepared and the kits in boxes ready for shipping to teams and
> the Kickstart venues.
> 
> That is also the date by which we are planning to confirm which teams have
> places at the competition, so we would need to know by that point how many teams
> we can support (i.e: how many kits we can hand out while still having enough
> spares). If we can know the number of teams sooner, then that would be better in
> order that we can give teams more notice of their place and thus more time for
> teachers to plan their trips to Kickstart.
> 
> We're planning to send out an email to teams soliciting applications early next
> week, which we hope will include the timeline with regard to confirmation of
> places.
> 
> While we appreciate that that's a tight deadline, we would also like to explore
> shipping Python 3 this year if possible. A caveat here is that we would rather
> that the API not change beyond what is strictly needed to support Python 3 as
> that would involve rewriting significant portions of documentation as well as
> re-training volunteers.
> 
> Please let us know whether you think this timeline is achievable.
> 
> Thanks,
> -- Competition Team

I'm not at all happy with the sign off, it definitely has the wrong tone, though I'm hoping this provides enough framework for someone to edit into something better.

**Comment by PeterJCLaw** [comment]
> We're planning to send out an email to teams soliciting applications early next week

This refers to #117, which in I'd actually like to get out this weekend so that it's in inboxes before the start of term.

Separately, the more I think about this, we might really need to know numbers well before the end of September. If we assume a month lead time for teachers, end of Sept confirmation would mean the earliest kickstart we can have is the end of October, which feels rather late.

**Comment by andybusse** [comment]
Sorry, only just picked this up - had a busy long weekend. I was planning to go much more colloquial and brief than that.

**Comment by PeterJCLaw** [comment]
Happened in an in-person meeting.
