### ISSUE TITLE
Repo Ownership

### ISSUE THREAD

**Issue by trickeydan** [srobo/competition-team-minutes#121]
This repo is currently listed under the Kit Team. I strongly suspect that this is not intentional. @RealOrangeOne

**Comment by RealOrangeOne** [comment]
This is an intentional side-effect of how GitHub's permissions work.

The repo has an explicit `read` permission for those in the 'Volunteers' team, which allows anyone to be assigned issues in the repo. As the Kit Team team is a child of the 'Volunteers' team, they inherit the permission.

I highly encourage the Kit Team's minutes repo be setup in the same fashion.

**Comment by PeterJCLaw** [comment]
Huh, do we need to have that explicit `read` permission? (Would the repo being public not achieve the same effect?)

**Comment by PeterJCLaw** [comment]
Scratch that, I can't read. It's to do with assignment.
